server:
  port: 8089
spring:
  mvc:
    static-path-pattern: /**
  resource:
    static-locations: classpath:/static/,classpath:/public/
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    url: jdbc:mysql://localhost:3306/cz_bank?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: root
    password: ei2ywGOqkl.k
    driver-class-name: com.mysql.jdbc.Driver

  jackson:
    default-property-inclusion: non_null
  #redis
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password:
    port: 6379

#mybatis plus
mybatis-plus:
  mapper-locations: classpath*:com/bank/api/**/xml/*Mapper.xml
  global-config:
    # ??MP3.0???banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: 4
      # 默认数据库表下划线命名
      table-underline: true
        #configuration:
      # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
      #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

