package com.bank.common.constant;

public class CommonConstant {
    public static final Integer STATUS_NORMAL = 0;
    public static final Integer STATUS_DISABLE = -1;
    public static final Integer DEL_FLAG_1 = 1;
    public static final Integer DEL_FLAG_0 = 0;
    public static final int LOG_TYPE_1 = 1;
    public static final int LOG_TYPE_2 = 2;
    public static final Integer SC_INTERNAL_SERVER_ERROR_500 = 500;
    public static final Integer SC_OK_200 = 200;
    public static final Integer NO_AUTHZ = 510;
    public static final int TOKEN_EXPIRE_TIME = 3600;
    public static final Integer MENU_TYPE_0 = 0;
    public static final Integer MENU_TYPE_1 = 1;
    public static final Integer MENU_TYPE_2 = 2;
    public static final String MSG_TYPE_UESR = "USER";
    public static final String MSG_TYPE_ALL = "ALL";
    public static final String NO_SEND = "0";
    public static final String HAS_SEND = "1";
    public static final String HAS_CANCLE = "2";
    public static final String HAS_READ_FLAG = "1";
    public static final String NO_READ_FLAG = "0";
    public static final String PRIORITY_L = "L";
    public static final String PRIORITY_M = "M";
    public static final String PRIORITY_H = "H";
    public static final String SMS_TPL_TYPE_0 = "0";
    public static final String SMS_TPL_TYPE_1 = "1";
    public static final String SMS_TPL_TYPE_2 = "2";
    public static final String STATUS_0 = "0";
    public static final String STATUS_1 = "1";
    public static final String ACT_SYNC_0 = "0";
    public static final String ACT_SYNC_1 = "1";
    public static final String MSG_CATEGORY_1 = "1";
    public static final String MSG_CATEGORY_2 = "2";
    public static final Integer RULE_FLAG_0 = 0;
    public static final Integer RULE_FLAG_1 = 1;
    public static final Integer USER_UNFREEZE = 1;
    public static final Integer USER_FREEZE = 2;
    public static final String DICT_TEXT_SUFFIX = "_dictText";
}
